name: Push components to Espressif Component Service

on:
  release:
    types: [published]

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: 'recursive'
      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v1
        with:
          name: "ESP32_Display_Panel"
          namespace: "lzw655"
          api_token: ${{secrets.IDF_COMPONENT_API_TOKEN}}
